# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTask',
            fields=[
                ('function_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('object_id', models.CharField(max_length=200)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'defined', b'ready to run'), (b'scheduled', b'scheduled'), (b'running', b'in progress'), (b'requested_cancel', b'cancellation requested'), (b'cancelled', b'cancelled'), (b'successful', b'finished successfully'), (b'unsuccessful', b'failed')], default=b'defined', max_length=200)),
                ('description', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('log', models.TextField(blank=True, default=b'', null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
