# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('key', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
