# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotasks', '0002_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='dependents',
            field=models.TextField(default=None, null=True),
        ),
    ]
